# Generated by Django 5.1.6 on 2025-03-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='specialty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
